name: Build on PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  REGISTRY: us-docker.pkg.dev/planetscale-registry/dev
  FLAVOR: mysql80

# Serialize workflow runs
# Also, if previous build hasn't finished, cancel it
concurrency:
  group: pr-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-tag-push-lite:
    name: vitess/lite

    runs-on: ubuntu-latest

    steps:
      - name: Checkout planetscale/vitess-private
        uses: actions/checkout@v2
        with:
          # Build HEAD of PR branch not branch merged into master
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          # Vitess build context causes tar header problem with containerd
          driver: docker

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.PLANETSCALE_GITHUB_PROD_SA_KEY }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/vitess/lite
          flavor: |
            latest=false
          tags: |
            type=ref,event=pr,prefix=${{ env.FLAVOR }}-pr-

      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/lite/Dockerfile.${{ env.FLAVOR }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          secrets: github_token=${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
