# This is a workflow that periodically pulls upstream to keep our fork up to date.
name: Pull Upstream

on:
  schedule:
    # Pull every hour at minute 50.
    # That way, build jobs that run at minute 0 will see the latest commits.
    - cron: "50 * * * *"

  push:
    # Also run on local changes.
    branches:
      - master

jobs:
  pull-upstream-master:
    name: pull upstream master

    runs-on: ubuntu-latest

    steps:
      - name: Checkout planetscale/vitess-private
        uses: actions/checkout@v2
        with:
          repository: planetscale/vitess-private
          fetch-depth: 0
          ref: master

      - name: Configure git
        run: |
          git config --global user.email "engineering+pull-upstream-workflow@planetscale.com"
          git config --global user.name "Pull Upstream Workflow"
          git config --global pull.rebase false

          git remote add upstream https://github.com/vitessio/vitess
          git remote set-url upstream --push disabled

      - name: Pull upstream master
        run: _planetscale/tools/pull-upstream-master.sh

      - name: Push origin master
        run: git push origin master
