name: Build on PR

on:
  pull_request_review:
    types:
      - submitted
      - edited

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

# Serialize workflow runs
# Also, if previous build hasn't finished, cancel it
concurrency:
  group: pr-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-tag-push-lite:
    name: vitess/lite

    runs-on: ubuntu-latest

    steps:
      - name: Checkout planetscale/vitess-private
        uses: actions/checkout@v2
        with:
          # Build HEAD of PR branch not branch merged into master
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          # Vitess build context causes tar header problem with containerd
          driver: docker

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.PLANETSCALE_GITHUB_PROD_SA_KEY }}

      - uses: actions/github-script@v6
        id: check-pr-state
        with:
          result-encoding: string
          script: |
            const full_repo = '${{ github.repository }}';
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: '${{ github.repository_owner }}',
              repo: full_repo.split('/')[1],
              pull_number: '${{ github.event.pull_request.number }}'
            });

            const review_states = new Map();
            for (const review of reviews) {
              console.log(`Reviewer: ${review.user.login} State: ${review.state}`);
              review_states.set(review.user.login, review.state);
            }

            let state = 'pending';
            for (const review_state of review_states.values()) {
              if (review_state == 'APPROVED') {
                state = 'approved';
              } else if (review_state = 'REQUEST_CHANGES') {
                state = 'request_changes';
                break;
              }
            }

            return state;

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ format('us-docker.pkg.dev/planetscale-registry/{0}/vitess/lite', steps.check-pr-state.outputs.result == 'approved' && 'prod' || 'dev') }}
          flavor: |
            latest=false
            prefix=mysql80-
          tags: |
            type=ref,event=pr,prefix=mysql80-pr-

      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/lite/Dockerfile.mysql80
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          secrets: github_token=${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.9

      - name: Set credentials for private go deps
        env:
          PLANETSCALE_ACTIONS_BOT_TOKEN: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://planetscalebot:${PLANETSCALE_ACTIONS_BOT_TOKEN}@github.com" >> ~/.git-credentials

      - name: Cache the go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test kmsbackup
        run: |
          echo '${{ secrets.VITESS_PRIVATE_AWS_CREDENTIALS }}' >> "$RUNNER_TEMP/aws.credentials"
          echo '${{ secrets.VITESS_PRIVATE_GCP_CREDENTIALS }}' >> "$RUNNER_TEMP/gcp.credentials"
          go test vitess.io/vitess/go/vt/mysqlctl/kmsbackup -v -race --aws-credentials-file "$RUNNER_TEMP/aws.credentials" --aws-credentials-profile vitess-private-ci
          go test vitess.io/vitess/go/vt/mysqlctl/gcsbackup -v -race --gcp-credentials-file "$RUNNER_TEMP/gcp.credentials"
