name: Nightly Build

on:
  # Enable manually trigger button in UI
  workflow_dispatch:

  schedule:
    # Every day at 5am UTC (9pm PST / 10pm PDT)
    - cron: '0 5 * * *'

jobs:
  build-tag-push-lite:
    name: vitess/lite

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ref:
          - main
          - latest
        image:
          - mysql80
        include:
          # Default image is tagged as 'latest'
          - image: mysql80
            ref: latest
            default: 'true'

    steps:
      - name: Checkout planetscale/vitess-private
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.ref }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          # Vitess build context causes tar header problem with containerd
          driver: docker

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.PLANETSCALE_GITHUB_PROD_SA_KEY }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ format('us-docker.pkg.dev/planetscale-registry/{0}/vitess/lite', matrix.ref == 'main' && 'prod' || 'dev') }}
          flavor: |
            latest=${{ matrix.default == 'true' }}
            prefix=${{ matrix.image }}-,onlatest=true
          tags: |
            type=raw,value={{date 'YYYY-MM-DD'}}.{{sha}}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/lite/Dockerfile.${{ matrix.image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          secrets: github_token=${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}

  slack-notify:
    name: "Send Slack Notification to #builds"
    needs:
      - build-tag-push-lite
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/_planetscale_slack-notify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
