name: check_imports
on: [push]
jobs:

  build:
    name: Check Imports
    runs-on: ubuntu-latest
    steps:
    - name: Configure git private repo access
      env:
        GITHUB_TOKEN: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
      run: |
        git config --global --add url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.9

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install goimports
      run: |
        go install golang.org/x/tools/cmd/goimports@latest

    - name: Run goimports
      run: |
        out=$(goimports -local vitess.io/vitess -l -w $(find . -name "*.go" | grep -v ".pb.go"))
        echo $out | grep go > /dev/null && echo -e "The following files are malformatted:\n$out" && exit 1 || echo "All the files are formatted correctly"
