name: comment_pull_request
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  comment_pull_request:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    name: Comment Pull Request with review checklist
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          comment_includes: 'Review Checklist'
          message: |
            ### Review Checklist
            
            Hello reviewers! :wave: Please follow the checklist that follows when reviewing this Pull Request.
            
            - [ ] Protobuf changes should be wire-compatible.

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}