name: Upgrade Downgrade Testing - Backups - Manual
on:
  push:
  pull_request:

concurrency:
  group: format('{0}-{1}', ${{ github.ref }}, 'Upgrade Downgrade Testing - Backups - Manual')
  cancel-in-progress: true

jobs:
  get_upgrade_downgrade_label:
    timeout-minutes: 5
    if: github.repository == 'vitessio/vitess'
    name: Get the Upgrade Downgrade pull request label
    runs-on: single-self-hosted
    outputs:
      hasLabel: ${{ steps.check_label.outputs.hasLabel }}

    steps:
      - name: Check Label for PR
        if: github.event_name == 'pull_request'
        uses: Dreamcodeio/pr-has-label-action@master
        id: check_label
        with:
          label: Skip Upgrade Downgrade

  get_latest_release:
    if: always() && (github.event_name != 'pull_request' || needs.get_upgrade_downgrade_label.outputs.hasLabel != 'true')
    name: Get latest release
    runs-on: single-self-hosted
    needs:
      - get_upgrade_downgrade_label
    outputs:
      latest_release: ${{ steps.output-latest-release-branch.outputs.latest_release_branch }}

    steps:
      - name: Check out to HEAD
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set output with latest release branch
        id: output-latest-release-branch
        run: |
          latest_release_branch=$(./tools/get_latest_release.sh ${{github.base_ref}})
          echo $latest_release_branch
          echo "::set-output name=latest_release_branch::${latest_release_branch}"

  # This job usually execute in ± 20 minutes
  upgrade_downgrade_test_manual:
    timeout-minutes: 40
    if: always() && (needs.get_latest_release.result == 'success')
    name: Run Upgrade Downgrade Test Backup Manual
    runs-on: single-self-hosted
    needs:
      - get_upgrade_downgrade_label
      - get_latest_release

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    # Checkout to the last release of Vitess
    - name: Checkout to the other version's code (${{ needs.get_latest_release.outputs.latest_release }})
      uses: actions/checkout@v2
      with:
        ref: ${{ needs.get_latest_release.outputs.latest_release }}

    - name: Get dependencies for the last release
      run: |
        go mod download

    - name: Building last release's binaries
      timeout-minutes: 5
      run: |
        source build.env
        make build
        mkdir -p /tmp/vitess-build-other/
        cp -R bin /tmp/vitess-build-other/
        rm -Rf bin/*

    # Checkout to this build's commit
    - name: Checkout to commit's code
      uses: actions/checkout@v2

    - name: Get dependencies for this commit
      run: |
        go mod download

    - name: Run make minimaltools
      run: |
        make minimaltools

    - name: Building the binaries for this commit
      timeout-minutes: 5
      run: |
        source build.env
        make build
        mkdir -p /tmp/vitess-build-current/
        cp -R bin /tmp/vitess-build-current/

    # We create a sharded Vitess cluster following the local example.
    # We also insert a few rows in our three tables.
    - name: Create the example Vitess cluster with all components using version N
      timeout-minutes: 5
      run: |
        source build.env ; cd examples/local
        ./backups/start_cluster.sh

    # Taking a backup
    - name: Take a backup of all the shards
      timeout-minutes: 2
      run: |
        source build.env ; cd examples/local
        ./backups/take_backups.sh

    # We insert more data in every table after the backup.
    # When we restore the backup made in the previous step, we do not want to see the rows we are about to insert now.
    # The initial number of rows for each table is:
    #     - customer: 5
    #     - product:  2
    #     - corder:   5
    # We shall see the same number of rows after restoring the backup.
    - name: Insert more data after the backup
      run: |
        source build.env ; cd examples/local ; source ./env.sh

        echo "insert into customer(email) values('new_user_1@domain.com');" | mysql
        echo "insert into product(sku, description, price) values('SKU-1009', 'description', 89);" | mysql
        echo "insert into corder(customer_id, sku, price) values(1, 'SKU-1009', 100);" | mysql

    # Stop all the tablets and remove their data
    - name: Stop tablets
      timeout-minutes: 5
      run: |
        source build.env ; cd examples/local
        ./backups/stop_tablets.sh

    # We downgrade: we use the version N-1 of vttablet
    - name: Downgrade - Swap binaries, use VTTablet N-1
      run: |
        source build.env

        rm -f $PWD/bin/vttablet
        cp /tmp/vitess-build-other/bin/vttablet $PWD/bin/vttablet
        vttablet --version

    # Starting the tablets again, they will automatically start restoring the last backup.
    - name: Start new tablets and restore
      timeout-minutes: 5
      run: |
        source build.env ; cd examples/local
        ./backups/restart_tablets.sh
        # give enough time to the tablets to restore the backup
        sleep 60

    # Count the number of rows in each table to make sure the restoration is successful.
    - name: Assert the number of rows in every table
      run: |
        source build.env ; cd examples/local ; source ./env.sh

        echo "select count(sku) from product;" | mysql 2>&1| grep 2
        echo "select count(email) from customer;" | mysql 2>&1| grep 5
        echo "select count(sku) from corder;" | mysql 2>&1| grep 5

    # We insert one more row in every table.
    - name: Insert more rows in the tables
      run: |
        source build.env ; cd examples/local ; source ./env.sh

        echo "insert into customer(email) values('new_user_2@domain.com');" | mysql
        echo "insert into product(sku, description, price) values('SKU-1011', 'description', 111);" | mysql
        echo "insert into corder(customer_id, sku, price) values(1, 'SKU-1011', 111);" | mysql

    # Taking a second backup of the cluster.
    - name: Take a second backup of all the shards
      timeout-minutes: 2
      run: |
        source build.env ; cd examples/local
        ./backups/take_backups.sh

    # Stopping the tablets so we can perform the upgrade.
    - name: Stop tablets
      timeout-minutes: 5
      run: |
        source build.env ; cd examples/local
        ./backups/stop_tablets.sh

    # We upgrade: we swap binaries and use the version N of the tablet.
    - name: Upgrade - Swap binaries, use VTTablet N
      run: |
        source build.env

        rm -f $PWD/bin/vttablet
        cp /tmp/vitess-build-current/bin/vttablet $PWD/bin/vttablet
        vttablet --version

    # Starting the tablets again and restoring the previous backup.
    - name: Start new tablets and restore
      timeout-minutes: 5
      run: |
        source build.env ; cd examples/local
        ./backups/restart_tablets.sh
        # give enough time to the tablets to restore the backup
        sleep 60

    # We count the number of rows in every table to check that the restore step was successful.
    - name: Assert the number of rows in every table
      run: |
        source build.env ; cd examples/local ; source ./env.sh

        echo "select count(sku) from product;" | mysql 2>&1| grep 3
        echo "select count(email) from customer;" | mysql 2>&1| grep 6
        echo "select count(sku) from corder;" | mysql 2>&1| grep 6

    - name: Stop the Vitess cluster
      if: always()
      run: |
        source build.env ; cd examples/local
        ./401_teardown.sh || true
