name: vtadmin-web unit tests

# In specifying the 'paths' property, we need to include the path to this workflow .yml file. 
# See https://github.community/t/trigger-a-workflow-on-change-to-the-yml-file-itself/17792/4)
on:
  push:
    paths:
      - '.github/workflows/vtadmin_web_unit_tests.yml'
      - 'web/vtadmin/**'

# defaults:
#   run:
#     working-directory: ./web/vtadmin

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git private repo access
        env:
          GITHUB_TOKEN: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
        run: |
          git config --global --add url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          # node-version should match package.json
          node-version: '16.13.0'

      - name: Install dependencies
        run: cd web/vtadmin && npm ci

      - name: Run unit tests
        run: cd web/vtadmin &&  CI=true npm run test
        
    # Cancel pending and in-progress runs of this workflow if a newer ref is pushed to CI.
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
